### ISSUE TITLE
Allow users to ignore SSL issues

### ISSUE THREAD

**Issue by alx-k** [WebBreacher/tilde_enum#29]
Currently the script just dies on us if the server cert can't be verified. You can fix this by creating a `urllib2` context:

```
# Ignore SSL issues context
import ssl
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE
```

and in `getWebServerResponse`:
```
response = urllib2.urlopen(req, context=ctx)
```

Surprisingly, still finding this script useful from time to time, but need support for self-signed certs :)

**Comment by WebBreacher** [comment]
Thanks for writing this up and suggesting the mod. Perhaps you could make it a pull request (https://help.github.com/articles/about-pull-requests/)? It'd make it easier to review and include in the project AND YOU GET PROPS!

**Comment by alx-k** [comment]
Thanks I'm looking into this. I've made a branch locally and tested the changes. I'm ready to make a pull request but after looking at your link it looks like I need a branch to make a pull request?

I'm getting permission denied when trying to push my branch to your repo:

```
~/Projects/tilde_enum $ git remote set-url origin git@github.com:WebBreacher/tilde_enum.git
~/Projects/tilde_enum $ git push origin ignore_ssl_issues 
ERROR: Permission to WebBreacher/tilde_enum.git denied to alx-k.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

(First time git contributor, my previous experience is limited to `git clone`)

**Comment by WebBreacher** [comment]
So I'll start off with this: "I am in NO way a good person to teach other people how to git. " With that out of the way, here goes.

1 - You will need to create a fork of the project so that you have a repository in your account/profile. Only I have access to add content to the master branch of the project.
2 - Once you make the fork, clone it locally and add your changes (you should be able to just copy your modded file in and save the changes)
3 - You, of course, will need to git add FILENAME and git commit -m "COMMENT HERE" FILENAME then GIT PUSH to add, commit and push your changes to YOUR fork.
4 - Once you do that, in Github, you will go to your repository where you should see a "CREATE PULL REQUEST" button. This sends your changes from your fork to my master project.
5 - Send the PULL request. I'll get an email and can examine your code. 
6 - If the code is solid, I'll merge it in (and give you props for helping make the tool better of course!)
7 - You will get notified when I merge your code. 

Sound good?

**Comment by alx-k** [comment]
Awesome! Thanks for the detailed write up. Pull request submitted :)

**Comment by WebBreacher** [comment]
Cool!
